# Generated by Django 2.2 on 2019-05-27 18:17

import os

from django.contrib.auth import get_user_model
from django.db import migrations


def add_user(apps, schema_editor):
    username = os.getenv("DJANGO_ADMIN_USER", None)
    password = os.getenv("DJANGO_ADMIN_PASSWORD", None)
    email = os.getenv("DJANGO_ADMIN_EMAIL", "dcbr-admin@gov.bc.ca")

    if username is not None and password is not None:
        print("Creating Django superuser...")
        User = get_user_model()  # get the currently active user model
        User.objects.create_superuser(username=username, password=password, email=email)
    else:
        print(
            "The environment variables DJANGO_ADMIN_USER and DJANGO_ADMIN_PASSWORD were not set, the Django admin user will need to be created manually."
        )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(add_user)]
