# Generated by Django 2.2 on 2019-08-19 19:18

from django.db import migrations

registration_text_content = """Dear {{user.name}},

It is with pleasure that the Ministry of Agriculture welcomes you to the Dog and Cat Operator Registry of the Ministry of Agriculture.

By registering your operation, you are actively contributing to the welfare of all animals across the Province of British Columbia.

Your registration number is: {{registration_number}}. If you have any questions, please don't hesitate to contact us at AgriServiceBC@gov.bc.ca
"""

registration_html_content = """Dear <strong>{{user.name}}</strong>,

<p>It is with pleasure that the Ministry of Agriculture welcomes you to the Dog and Cat Operator Registry of the Ministry of Agriculture.</p>


<p>
By registering your operation, you are actively contributing to the welfare of all animals across the Province of British Columbia.</p>
"""

reminder_text_content = """Dear {{user.name}},

Your registration number {{registration_number}} is about to expire. If you have any questions, please don't hesitate to contact us at AgriServiceBC@gov.bc.ca
"""

reminder_html_content = """Dear <strong>{{user.name}}</strong>,

<p>Your registration number {{registration_number}} is about to expire. If you have any questions, please don't hesitate to contact us at AgriServiceBC@gov.bc.ca</p>
"""


def create_registration_template(apps, schema_editor):
    EmailTemplate = apps.get_model("post_office", "EmailTemplate")

    registration_email = EmailTemplate(
        name="registration_email",
        description="Confirmation of successful registration to DCBR",
        subject="Registration #{{registration_number}} to the Ministry of Agriculture's Dog and Cat Operator registry",
        content=registration_text_content,
        html_content=registration_html_content,
    )
    registration_email.save()


def create_reminder_template(apps, schema_editor):
    EmailTemplate = apps.get_model("post_office", "EmailTemplate")

    registration_email = EmailTemplate(
        name="reminder_email",
        description="Reminder of registration renewal for DCBR",
        subject="Registration #{{registration_number}} to Dog and Cat Operator Registry is about to expire",
        content=reminder_text_content,
        html_content=reminder_html_content,
    )
    registration_email.save()


class Migration(migrations.Migration):

    dependencies = [("post_office", "0001_initial")]

    operations = [
        migrations.RunPython(create_registration_template),
        migrations.RunPython(create_reminder_template),
    ]
