# Generated by Django 2.2 on 2019-08-19 19:18

from django.db import migrations

registration_text_content = """Hello {{operator.first_name}},

Thank you for successfully completing the BC Commercial Cat and Dog Breeder registration online. This email is confirmation that your dog/cat breeding and/or selling Registration Number is active.

Your registration number is: {{registration_number}}. 

This email provides you with important information regarding your registration and on how to maintain compliance with the Cat and Dog Commercial Breeding Regulation. The link provided takes you directly to the <a href="https://www2.qa.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/agriculture-and-seafood/animal-and-crops/animal-health/animal-welfare/cat_and_dog_commercial_breeder_regulation.pdf">Cat and Dog Commercial Breeding Regulation</a>

The attachment is your Certificate of Registration.  You must always have this Certificate visible in your operation for consumers to see.

We would be grateful for any comments or feedback you have on our new online registration system.  Please feel free to provide input on the online registration system to XXX so that we can improve the system in the future.  Thank you for your time.

Kind regards,
(name)
"""

registration_html_content = """Hello <strong>{{operator.first_name}}</strong>,

<p>Thank you for successfully completing the BC Commercial Cat and Dog Breeder registration online. This email is confirmation that your dog/cat breeding and/or selling Registration Number is active.

Your registration number is: {{registration_number}}.</p>


<p>
This email provides you with important information regarding your registration and on how to maintain compliance with the Cat and Dog Commercial Breeding Regulation. The link provided takes you directly to the <a href="https://www2.qa.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/agriculture-and-seafood/animal-and-crops/animal-health/animal-welfare/cat_and_dog_commercial_breeder_regulation.pdf">Cat and Dog Commercial Breeding Regulation</a>

The attachment is your Certificate of Registration.  You must always have this Certificate visible in your operation for consumers to see.</p>

<p>We would be grateful for any comments or feedback you have on our new online registration system.  Please feel free to provide input on the online registration system to XXX so that we can improve the system in the future.  Thank you for your time.</p>

<p>Kind regards,</p>
<p>(name)</p>
"""

reminder_text_content = """Hello {{operator.first_name}},

This email is to inform you that your BC Cat and Dog Breeding Registration is soon expiring and needs renewal. 

You are required as per Section XXXX of the Cat and Dog Commercial Breeding Regulation to renew your registration within 30 days from this email.

Please follow the link provided and select the “Renew” button to start the renewal process and your new Certificate of Registration. Once the process is completed you will receive a new Certificate of Registration and you must replace your old version.

Kind regards.
(name)
"""

reminder_html_content = """Hello <strong>{{operator.first_name}}</strong>,
<p>This email is to inform you that your BC Cat and Dog Breeding Registration is soon expiring and needs renewal. </p>

<p>You are required as per Section XXXX of the Cat and Dog Commercial Breeding Regulation to renew your registration within 30 days from this email.</p>

<p>Please follow the link provided and select the “Renew” button to start the renewal process and your new Certificate of Registration. Once the process is completed you will receive a new Certificate of Registration and you must replace your old version.</p>

<p>Kind regards.</p>
<p>(name)</p>
"""


def create_registration_template(apps, schema_editor):
    EmailTemplate = apps.get_model("post_office", "EmailTemplate")

    registration_email = EmailTemplate(
        name="registration_email",
        description="Confirmation of successful registration to DCBR",
        subject="Registration #{{registration_number}} to the Ministry of Agriculture's Dog and Cat Breeder registry",
        content=registration_text_content,
        html_content=registration_html_content,
    )
    registration_email.save()


def create_reminder_template(apps, schema_editor):
    EmailTemplate = apps.get_model("post_office", "EmailTemplate")

    registration_email = EmailTemplate(
        name="reminder_email",
        description="Reminder of registration renewal for DCBR",
        subject="Registration #{{registration_number}} to Dog and Cat Operator Registry is about to expire",
        content=reminder_text_content,
        html_content=reminder_html_content,
    )
    registration_email.save()


class Migration(migrations.Migration):

    dependencies = [("post_office", "0001_initial")]

    operations = [
        migrations.RunPython(create_registration_template),
        migrations.RunPython(create_reminder_template),
    ]
