# Generated by Django 2.2 on 2019-05-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address1', models.CharField(max_length=200)),
                ('numDogs', models.IntegerField()),
                ('numCats', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
