# Generated by Django 2.2 on 2019-05-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_operator_address2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='address2',
            new_name='timestamp',
        ),
    ]
