# Generated by Django 2.2 on 2019-05-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_auto_20190506_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
