# Generated by Django 2.2 on 2019-06-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk_factor_operation',
            name='operator_type',
            field=models.CharField(choices=[('DOG', 'dog'), ('CAT', 'cat'), ('DOG & CAT', 'dog & cat')], default='DOG', max_length=10),
        ),
    ]
