# Generated by Django 2.2 on 2019-06-14 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='comm_type',
            new_name='comm_pref',
        ),
        migrations.AddField(
            model_name='operator',
            name='email_address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='operator',
            name='phone_num',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='risk_factor_operation',
            name='operation_type',
            field=models.CharField(choices=[('DOG', 'dog'), ('CAT', 'cat'), ('DOG & CAT', 'dog & cat')], default='DOG & CAT', max_length=10),
        ),
        migrations.AlterField(
            model_name='risk_factor_operation',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factor_operations', related_query_name='risk_factor_operations', to='api.Operator'),
        ),
    ]
