# Generated by Django 2.2 on 2019-06-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='operation_URL',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
