# Generated by Django 2.2 on 2019-06-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_risk_factor_operation_operator_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk_factor_operation',
            name='operator_type',
        ),
    ]
