# Generated by Django 2.2 on 2019-06-14 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190614_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='operator_type',
            new_name='operation_type',
        ),
        migrations.RenameField(
            model_name='risk_factor_operation',
            old_name='operation_type',
            new_name='animal_type',
        ),
    ]
