# Generated by Django 2.2 on 2019-05-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190527_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='slug',
        ),
    ]
