# Generated by Django 2.2 on 2019-05-28 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190527_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='regNum',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.Operator'),
            preserve_default=False,
        ),
    ]
