# Generated by Django 2.2 on 2019-06-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190618_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='animal_type',
        ),
        migrations.AddField(
            model_name='risk_factor_operation',
            name='animal_type',
            field=models.CharField(choices=[('DOG', 'dog'), ('CAT', 'cat'), ('DOG & CAT', 'dog & cat')], default='DOG & CAT', max_length=10),
        ),
    ]
