# Generated by Django 2.2 on 2019-05-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190527_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='regNum',
            field=models.TextField(),
        ),
    ]
