# Generated by Django 2.2 on 2019-06-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190618_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk_factor_operation',
            name='animal_type',
            field=models.CharField(choices=[('DOG', 'DOG'), ('CAT', 'CAT'), ('DOG & CAT', 'DOG & CAT')], default='DOG & CAT', max_length=10),
        ),
    ]
