# Generated by Django 2.2 on 2019-05-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190528_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='regNum',
            field=models.CharField(max_length=32),
        ),
    ]
