# Generated by Django 2.2 on 2019-06-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190618_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk_factor_operation',
            name='operation_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
