# Generated by Django 2.2 on 2019-05-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190528_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='regNum',
            field=models.CharField(max_length=14),
        ),
    ]
