# Generated by Django 2.2 on 2019-06-18 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_risk_factor_operation_operation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk_factor_operation',
            name='operation_name',
        ),
    ]
