# Generated by Django 2.2 on 2019-05-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190529_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNum', models.CharField(max_length=14)),
                ('op_firstName', models.CharField(max_length=32)),
                ('op_middleName', models.CharField(max_length=50)),
                ('op_lastName', models.CharField(max_length=50)),
                ('soc_1', models.BooleanField(default=False)),
                ('soc_2', models.BooleanField(default=False)),
                ('soc_3', models.BooleanField(default=False)),
                ('soc_4', models.BooleanField(default=False)),
                ('soc_5', models.BooleanField(default=False)),
                ('soc_6', models.BooleanField(default=False)),
                ('soc_7', models.BooleanField(default=False)),
                ('soc_8', models.BooleanField(default=False)),
                ('soc_9', models.BooleanField(default=False)),
                ('soc_10', models.BooleanField(default=False)),
                ('soc_11', models.BooleanField(default=False)),
                ('soc_1_comment', models.TextField()),
                ('soc_2_comment', models.TextField()),
                ('soc_3_comment', models.TextField()),
                ('soc_4_comment', models.TextField()),
                ('soc_5_comment', models.TextField()),
                ('soc_6_comment', models.TextField()),
                ('soc_7_comment', models.TextField()),
                ('soc_8_comment', models.TextField()),
                ('soc_9_comment', models.TextField()),
                ('soc_10_comment', models.TextField()),
                ('soc_11_comment', models.TextField()),
                ('soc_12_comment', models.TextField()),
                ('soc_13_comment', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Inspections',
            },
        ),
    ]
