# Generated by Django 2.2 on 2019-06-19 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_risk_factor_operation_operation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk_factor_operation',
            name='num_employees',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
