# Generated by Django 2.2 on 2019-06-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_risk_factor_operation_num_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk_factor_operation',
            name='num_employees',
        ),
    ]
