# Generated by Django 2.2 on 2019-06-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_risk_factor_operation_num_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association_membership',
            name='assoc_URL',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='association_membership',
            name='membership_num',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
