# Generated by Django 2.2 on 2019-06-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190624_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('PRI', 'Primary'), ('OPN', 'Operation')], default='PRI', max_length=3),
        ),
    ]
