# Generated by Django 2.2 on 2019-06-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190624_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk_factor_operation',
            name='perm_id_type',
            field=models.CharField(choices=[('TATTOO', 'TATTOO'), ('MICROCHIP', 'MICROCHIP'), ('OTHER', 'OTHER')], default='TATTOO', max_length=10),
        ),
    ]
