# Generated by Django 2.2 on 2019-06-25 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190625_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk_factor_animal',
            old_name='num_traded',
            new_name='num_cat_transferred',
        ),
        migrations.RenameField(
            model_name='risk_factor_animal',
            old_name='num_leased',
            new_name='num_dog_leased',
        ),
        migrations.RenameField(
            model_name='risk_factor_animal',
            old_name='num_sold',
            new_name='num_dog_sold',
        ),
        migrations.RenameField(
            model_name='risk_factor_animal',
            old_name='num_transferred',
            new_name='num_dog_traded',
        ),
        migrations.AddField(
            model_name='risk_factor_animal',
            name='num_cat_leased',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='risk_factor_animal',
            name='num_cat_sold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='risk_factor_animal',
            name='num_cat_traded',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='risk_factor_animal',
            name='num_dog_transferred',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
