# Generated by Django 2.2 on 2019-07-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190625_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='reg_num',
            field=models.CharField(max_length=14, verbose_name="Operator's registration name"),
        ),
    ]
