# Generated by Django 2.2 on 2019-07-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190708_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='reg_num',
            field=models.CharField(max_length=14, verbose_name='Operator REG #'),
        ),
    ]
