# Generated by Django 2.2 on 2019-07-08 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190708_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name_plural': 'Operators1'},
        ),
    ]
