# Generated by Django 2.2 on 2019-07-08 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190708_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name_plural': 'Operators'},
        ),
    ]
