# Generated by Django 2.2 on 2019-07-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190708_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Operators : breeders and sellers', 'verbose_name_plural': 'Operators'},
        ),
    ]
