# Generated by Django 2.2 on 2019-07-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190708_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='created',
            new_name='create_timestamp',
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='updated',
            new_name='update_timestamp',
        ),
        migrations.AlterField(
            model_name='operator',
            name='comm_pref',
            field=models.CharField(choices=[('Email', 'email'), ('Mail', 'mail')], default='Email', max_length=10, verbose_name='Communication method'),
        ),
    ]
