# Generated by Django 2.2 on 2019-08-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190708_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('CANCELLED', 'CANCELLED'), ('PENDING_PAYMENT', 'PENDING_PAYMENT'), ('PENDING_INSPECTOR_REVIEW', 'PENDING_INSPECTOR_REVIEW'), ('PENDING_RENEWAL', 'PENDING_RENEWAL')], default='ACTIVE', max_length=50)),
            ],
            options={
                'verbose_name': 'new registration',
                'verbose_name_plural': 'Registrations',
            },
        ),
    ]
