# Generated by Django 2.2 on 2019-07-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190722_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='operation_type',
            field=models.CharField(choices=[('BREEDER', 'BREEDER'), ('SELLER', 'SELLER'), ('BREEDER&SELLER', 'BREEDER&SELLER')], default='BREEDER', max_length=20),
        ),
    ]
