# Generated by Django 2.2 on 2019-08-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190722_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk_factor_operation',
            name='perm_id_type',
            field=models.CharField(choices=[('TATTOO', 'TATTOO'), ('MICROCHIP', 'MICROCHIP'), ('OTHER', 'OTHER'), ('NOT_APPLICABLE', 'NOT_APPLICABLE')], default='TATTOO', max_length=10),
        ),
    ]
