# Generated by Django 2.2 on 2019-08-19 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190816_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('CANCELLED', 'CANCELLED'), ('PENDING_PAYMENT', 'PENDING_PAYMENT'), ('PENDING_INSPECTOR_REVIEW', 'PENDING_INSPECTOR_REVIEW'), ('PENDING_RENEWAL', 'PENDING_RENEWAL')], default='ACTIVE', max_length=50)),
            ],
            options={
                'verbose_name': 'new registration',
                'verbose_name_plural': 'RegistrationNumbers',
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='association_membership',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='risk_factor_animal',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='risk_factor_operation',
            name='operator',
        ),
        migrations.AlterField(
            model_name='inspection',
            name='reg_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='api.RegistrationNumber'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='soc_1_comment',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='operator',
            name='reg_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator', related_query_name='operators', to='api.RegistrationNumber'),
        ),
        migrations.AddField(
            model_name='address',
            name='reg_num',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', related_query_name='addresses', to='api.RegistrationNumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='association_membership',
            name='reg_num',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='api.RegistrationNumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk_factor_animal',
            name='reg_num',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='risk_factor_animals', related_query_name='risk_factor_animals', to='api.RegistrationNumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk_factor_operation',
            name='reg_num',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='risk_factor_operations', related_query_name='risk_factor_operations', to='api.RegistrationNumber'),
            preserve_default=False,
        ),
    ]
