# Generated by Django 2.2 on 2019-08-22 03:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190816_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_Risk_Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('DOG', 'DOG'), ('CAT', 'CAT')], default='DOG', max_length=10)),
                ('num_breeds', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_females_intact', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_litter', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_sold', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_transferred', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_traded', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_leased', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Animal_Risk_Factors',
            },
        ),
        migrations.CreateModel(
            name='Operation_Risk_Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accidental_breeding', models.BooleanField(default=False)),
                ('num_workers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('has_vet', models.BooleanField(default=False)),
                ('has_perm_id', models.BooleanField(default=False)),
                ('perm_id_type', models.CharField(choices=[('TATTOO', 'TATTOO'), ('MICROCHIP', 'MICROCHIP'), ('OTHER', 'OTHER'), ('NOT_APPLICABLE', 'NOT_APPLICABLE')], default='NOT_APPLICABLE', max_length=15)),
                ('perm_id_other', models.CharField(blank=True, default='', max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Operation_Risk_Factors',
            },
        ),
        migrations.CreateModel(
            name='Registration_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('CANCELLED', 'CANCELLED'), ('PENDING_PAYMENT', 'PENDING_PAYMENT'), ('PENDING_INSPECTOR_REVIEW', 'PENDING_INSPECTOR_REVIEW'), ('PENDING_RENEWAL', 'PENDING_RENEWAL')], default='ACTIVE', max_length=50)),
            ],
            options={
                'verbose_name': 'new registration',
                'verbose_name_plural': 'Registration_Numbers',
            },
        ),
        migrations.RemoveField(
            model_name='risk_factor_operation',
            name='operator',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='type',
            new_name='address_type',
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='create_timestamp',
            new_name='created_timestamp',
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='update_timestamp',
            new_name='updated_timestamp',
        ),
        migrations.RemoveField(
            model_name='address',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='association_membership',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='reg_num',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='reg_num',
        ),
        migrations.AlterField(
            model_name='association_membership',
            name='membership_num',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='operator',
            name='email_address',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operation_URL',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operation_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='operator',
            name='phone_num',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.DeleteModel(
            name='Risk_Factor_Animal',
        ),
        migrations.DeleteModel(
            name='Risk_Factor_Operation',
        ),
        migrations.AddField(
            model_name='operation_risk_factor',
            name='registration_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_risk_factors', related_query_name='operation_risk_factors', to='api.Registration_Number'),
        ),
        migrations.AddField(
            model_name='animal_risk_factor',
            name='registration_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_risk_factors', related_query_name='animals_risk_factors', to='api.Registration_Number'),
        ),
        migrations.AddField(
            model_name='address',
            name='registration_Number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', related_query_name='addresses', to='api.Registration_Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='association_membership',
            name='registration_Number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='api.Registration_Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='registration_Number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='api.Registration_Number'),
        ),
        migrations.AddField(
            model_name='operator',
            name='registration_Number',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='operator', related_query_name='operators', to='api.Registration_Number'),
            preserve_default=False,
        ),
    ]
