# Generated by Django 2.2 on 2019-08-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190819_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='reg_num',
            new_name='registrationNumber',
        ),
    ]
