# Generated by Django 2.2 on 2019-09-10 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20190910_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_risk_factor',
            name='num_animals',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
