# Generated by Django 2.2 on 2019-09-10 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_animal_risk_factor_num_animals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=32)),
                ('middle_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('previous_registation_number', models.CharField(blank=True, default='', max_length=14)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('registration_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='api.Registration')),
            ],
            options={
                'verbose_name_plural': 'Renewals',
            },
        ),
    ]
