# Generated by Django 2.2 on 2019-08-20 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190819_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='type',
            new_name='address_type',
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='create_timestamp',
            new_name='created_timestamp',
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='update_timestamp',
            new_name='updated_timestamp',
        ),
        migrations.AlterField(
            model_name='association_membership',
            name='membership_num',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='operator',
            name='email_address',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operation_URL',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operation_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='operator',
            name='phone_num',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='operator',
            name='registrationNumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator', related_query_name='operators', to='api.RegistrationNumber'),
        ),
    ]
