# Generated by Django 2.2 on 2019-09-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='region_type',
            field=models.CharField(choices=[('ALBERNI_CLAYOQUOT', 'Alberni-Clayoquot'), ('BULKLEY-NECHAKO', 'Buckley-Nechako'), ('CAPITAL', 'Capital'), ('CARIBOO', 'Cariboo'), ('CENTRAL COAST', 'Central Coast'), ('CENTRAL KOOTENAY', 'Central Kootenay'), ('CENTRAL OKANAGAN', 'Central Okanagan'), ('COLUMBIA SHUSWAP', 'Columbia-Shuswap'), ('COMOX VALLEY', 'Comox Valley'), ('COWICHAN VALLEY', 'Cowichan Valley'), ('EAST_KOOTENAY', 'East Kootenay'), ('FRASER_VALLEY', 'Fraser Valley'), ('FRASER-FORT GEORGE', 'Fraser-Fort George'), ('ISLANDS TRUST', 'Islands Trust'), ('Kitimat Stikine', 'Kitimat Stikine'), ('Kootenay Boundary', 'Kootenay Boundary'), ('Metro Vancouver', 'Metro Vancouver'), ('Mount Waddington', 'Mount Waddington'), ('Nanaimo', 'Nanaimo'), ('North Okanagan', 'North Okanagan'), ('North Coast', 'North Coast'), ('Okanagan-Similkameen', 'Okanagan-Similkameen'), ('Peace River', 'Peace River'), ('Gathet', 'Gathet'), ('Squamish-Lillooet', 'Squamish-Lillooet'), ('Strathcona', 'Strathcona'), ('Sunshine Coast', 'Sunshine Coast'), ('Thompson-Nicola', 'Thompson-Nicola')], default='', max_length=20),
        ),
    ]
