# Generated by Django 2.2 on 2019-09-12 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_renewal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_full_name', models.CharField(default='', max_length=50)),
                ('operator_first_name', models.CharField(max_length=32)),
                ('operator_middle_name', models.CharField(blank=True, default='', max_length=50)),
                ('operator_last_name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('Nutrition', models.BooleanField(default=False)),
                ('Nutrition_notes', models.TextField(blank=True, default='')),
                ('Grooming_and_Nail_Care', models.BooleanField(default=False)),
                ('Grooming_and_Nail_Care_notes', models.TextField(blank=True, default='')),
                ('Cleaning_and_Disinfection', models.BooleanField(default=False)),
                ('Cleaning_and_Disinfection_notes', models.TextField(blank=True, default='')),
                ('Environment_and_Housing', models.BooleanField(default=False)),
                ('Environment_and_Housing_notes', models.TextField(blank=True, default='')),
                ('Socialization', models.BooleanField(default=False)),
                ('Socialization_notes', models.TextField(blank=True, default='')),
                ('Breeding', models.BooleanField(default=False)),
                ('Breeding_notes', models.TextField(blank=True, default='')),
                ('Whelping_and_Queening', models.BooleanField(default=False)),
                ('Whelping_and_Queening_notes', models.TextField(blank=True, default='')),
                ('Veterinary_Care', models.BooleanField(default=False)),
                ('Veterinary_Care_notes', models.TextField(blank=True, default='')),
                ('Health_Care_Protocol', models.BooleanField(default=False)),
                ('Health_Care_Protocol_notes', models.TextField(blank=True, default='')),
                ('Transportation', models.BooleanField(default=False)),
                ('Transportation_notes', models.TextField(blank=True, default='')),
                ('Plans', models.BooleanField(default=False)),
                ('Plans_notes', models.TextField(blank=True, default='')),
                ('Registration_and_Record_Keeping', models.BooleanField(default=False)),
                ('Registration_and_Record_Keeping_notes', models.TextField(blank=True, default='')),
                ('Responsibilities_of_the_Operator', models.BooleanField(default=False)),
                ('Responsibilities_of_the_Operator_notes', models.TextField(blank=True, default='')),
                ('Exercise', models.BooleanField(default=False)),
                ('Exercise_notes', models.TextField(blank=True, default='')),
                ('Handling_and_Training', models.BooleanField(default=False)),
                ('Handling_and_Training_notes', models.TextField(blank=True, default='')),
                ('Euthanasia', models.BooleanField(default=False)),
                ('Euthanasia_notes', models.TextField(blank=True, default='')),
                ('registration_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='api.Registration')),
            ],
            options={
                'verbose_name_plural': 'Inspections',
            },
        ),
        migrations.DeleteModel(
            name='Inspection',
        ),
    ]
