# Generated by Django 2.2 on 2019-09-12 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190912_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='updated_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
