# Generated by Django 2.2 on 2019-09-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20190912_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='comm_pref',
            field=models.CharField(choices=[('Email', 'Email'), ('Mail', 'Mail'), ('Phone', 'Phone')], default='Email', max_length=10, verbose_name='Communication method'),
        ),
    ]
