# Generated by Django 2.2 on 2019-09-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_address_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='renewal',
            name='previous_registation_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
