# Generated by Django 2.2 on 2019-09-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20190919_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Cleaning_and_Disinfection',
            new_name='Containment',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Cleaning_and_Disinfection_notes',
            new_name='Containment_notes',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Environment_and_Housing',
            new_name='Environment',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Environment_and_Housing_notes',
            new_name='Environment_notes',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Health_Care_Protocol',
            new_name='Food_and_Water',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Health_Care_Protocol_notes',
            new_name='Food_and_Water_notes',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Nutrition',
            new_name='Handling',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Nutrition_notes',
            new_name='Handling_notes',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Plans',
            new_name='Health_Care',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Plans_notes',
            new_name='Health_Care_notes',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Registration_and_Record_Keeping',
            new_name='Protection_from_Injury_and_Illness',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Registration_and_Record_Keeping_notes',
            new_name='Protection_from_Injury_and_Illness_notes',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Responsibilities_of_the_Operator',
            new_name='Queening_and_Whelping',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Responsibilities_of_the_Operator_notes',
            new_name='Queening_and_Whelping_notes',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Socialization',
            new_name='Record_Keeping',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Socialization_notes',
            new_name='Record_Keeping_notes',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Whelping_and_Queening',
            new_name='Required_Plans',
        ),
        migrations.RenameField(
            model_name='inspection_report',
            old_name='Whelping_and_Queening_notes',
            new_name='Required_Plans_notes',
        ),
        migrations.RenameField(
            model_name='renewal',
            old_name='previous_registation_number',
            new_name='previous_registration_number',
        ),
        migrations.RemoveField(
            model_name='association_membership',
            name='assoc_URL',
        ),
        migrations.RemoveField(
            model_name='association_membership',
            name='membership_num',
        ),
        migrations.AddField(
            model_name='inspection_report',
            name='Socialization_and_Exercise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspection_report',
            name='Socialization_and_Exercise_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inspection_report',
            name='Tethering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspection_report',
            name='Tethering_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='registration',
            name='num_locations',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
