# Generated by Django 2.2 on 2019-09-19 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20190919_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renewal',
            old_name='previous_registation_number',
            new_name='previous_registration_number',
        ),
        migrations.AddField(
            model_name='registration',
            name='expiry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
