# Generated by Django 2.2 on 2019-09-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20190920_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='POBox',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
