# Generated by Django 2.2 on 2019-09-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20190919_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registration_date_str',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
