# Generated by Django 2.2 on 2019-09-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20190919_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='num_locations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registration',
            name='expiry_date',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
