# Generated by Django 2.2 on 2019-09-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_address_pobox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='num_locations',
        ),
    ]
