# Generated by Django 2.2 on 2019-09-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_registration_num_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('MAIL', 'Mailing'), ('OPN', 'Operation')], default='MAIL', max_length=4),
        ),
    ]
