# Generated by Django 2.2 on 2019-09-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20190925_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal',
            name='expiry_date',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
