# Generated by Django 2.2 on 2019-10-10 04:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_renewal_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='created_timestamp',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='updated_timestamp',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='created_timestamp',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='updated_timestamp',
            new_name='updated_date',
        ),
        migrations.AddField(
            model_name='registration',
            name='expiry_date',
            field=models.DateTimeField(default=api.models.Registration.default_expiry_date),
        ),
    ]
