# Generated by Django 2.2 on 2019-10-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20191009_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renewal',
            old_name='expiry_date',
            new_name='previous_registration_date',
        ),
    ]
